"""cascade delete on departments and employees

Revision ID: 5382677a8c59
Revises: dc934d56c108
Create Date: 2026-05-14 06:17:18.787704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5382677a8c59'
down_revision: Union[str, None] = 'dc934d56c108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('departments_parent_id_fkey', 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'departments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('employees_department_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_department_id_fkey', 'employees', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key('departments_parent_id_fkey', 'departments', 'departments', ['parent_id'], ['id'])
    # ### end Alembic commands ###
